### ISSUE TITLE
Enum types supported for URI Parameters

### ISSUE THREAD

**Issue by anallely** [gextech/raml2code-retrofit#1]
I have the following resource definition

```
/website/{idType}/{id}:
  displayName: Website
  type: member
  uriParameters:
    idType:
      displayName: The criteria to identify the website resource
      enum: [slug, domain]

```

I am trying to define that {idType} must only accept 'slug' or 'domain' values.
- It could be nice at least to generate documentation on generated retrofit client which indicates supported values
- It could be nicer if retrofit clients generates a method for each supported value. Example: getWebsitesBySlug and getWebsitesByDomain.

Paste bin whole index.raml:  http://pastebin.com/mV1wN5eU
